trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageRepository: 'schoolapp'
  containerRegistry: 'schoolapp-acr'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

steps:

- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(containerRegistry)
    tags: |
      $(tag)
      latest

- task: KubernetesManifest@1
  displayName: Deploy to AKS
  inputs:
    action: deploy
    manifests: |
      k8s/deployment.yaml
      k8s/service.yaml
    containers: |
      schoolapp2002.azurecr.io/schoolapp:$(tag)
